name: Run tests

on:  
  push:
    branches: 
      - master
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Run chart-testing (install)
        run: ct install
      
#      - name: 'Deploy'
#        id:  'deployonK8s'
#        uses: 'deliverybot/helm@master'
#        with:
#           namespace: production
#           release: flink
#           value-files: './config/production.yml'
#           token: '${{ secrets.CR_TOKEN }}'
#           chart: 'charts/apache-flink'
#           helm: helm3
#        
 #       env:
 #          HELM_DEBUG: 1
 #          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
 #          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 #          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
            PLAN: "FlinkChart\n${{ steps.deployonK8s.outputs.stdout }}"
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
               const output = `#### Deployment on Kubernetes 📖\`${{ steps.deployonK8s.outcome }}\`
               <details><summary>Show Deployment</summary>
               \`\`\`${process.env.PLAN}\`\`\`
               </details>
               *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

               github.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: output
                })
                
  publish:
    
    needs: deploy 
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts
