name: Run tests

on:  
  pull_request:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Deploy'
        id:  'deployonK8s'
        uses: 'deliverybot/helm@master'
        with:
           namespace: production
           release: flink
           value-files: './config/production.yml'
           token: '${{ secrets.CR_TOKEN }}'
           chart: 'charts/apache-flink'
           helm: helm3
        
        env:
           HELM_DEBUG: 1
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

      - name: Update Pull Request
        uses: actions/github-script@0.9.0
        if: github.event_name == 'pull_request'
        env:
            PLAN: "FlinkChart\n${{ steps.deployonK8s.outputs.stdout }}"
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
               const output = `#### Deployment on Kubernetes 📖\`${{ steps.deployonK8s.outcome }}\`
               <details><summary>Show Deployment</summary>
               \`\`\`${process.env.PLAN}\`\`\`
               </details>
               *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

               github.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: output
                })
        
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts
