name: Update Helm Repo

on:
  push:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Publish Helm charts
        uses: J12934/helm-gh-pages-action@master
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts
