name: release
on:
  push:
    tags: '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: 'Deploy'
        uses: 'deliverybot/helm@master'
        with:
          token: '${{ github.token }}'
          chart: 'apache-flink'
        
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
        
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.CR_TOKEN }}
          charts_dir: charts
